project:
  type: website
  output-dir: docs

website:
  title: "the observatory"
  favicon: resources/favicon.ico
  description: "Welcome to Mike Lee's blog"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/leemun1
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 17px
    mainfont: "'Roboto Slab', 'Noto Serif KR', serif"
