project:
  type: website

website:
  title: "dots"
  site-url: https://www.mikemunkyulee.com/blog
  description: "Welcome to Mike Lee's blog"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/leemun1
format:
  html:
    theme: flatly
    css: styles.css



