---
title: "Hello, world! 👋"
about:
  template: solana
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/mike-munkyu-lee
    - icon: github
      text: Github
      href: https://github.com/leemun1

---

Hi there! My name is Mike Lee.<br>
Welcome to my little corner of the internet ✨

## Education

##### **University of Toronto** | Toronto, Canada
Bachelor of Commerce<br>
Graduated in 2018

## Work Experience

##### **PartnerStack** | Software Engineer
May 2021 - Present

Worked on the frontend and backend for the company's [Partnership management software platform](https://partnerstack.com/platform/platform-demo-video){.external target="_blank"}, with a focus on payment workflows.

- Developed and maintained integration with payment service providers (e.g., Stripe)
- Developed internal reporting and monitoring tools for the payment system
- Led initiative to modernize backend unit testing suite, reducing total execution time by 30%  
- Worked on Vue 3 migration, and localization projects on the frontend

##### **Mosaic Manufacturing** | Software Engineer
August 2018 - May 2021

Worked on the frontend, backend, and the cloud infrastructure for [Canvas](https://www.mosaicmfg.com/pages/canvas){.external target="_blank"}, a 3D printing software platform.

- Restructured centralized backend system into distributed architecture for core tasks
- Implemented features for rendering and customizing 3D models
- Developed and maintained Node.js serverless REST API
- Led development of React frontend